<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="mac.local" ignored="0" name="exampletest12" tests="1" failures="1" timestamp="07 Feb 2019 04:11:14 GMT" time="32.944" errors="0">
  <testcase name="testTerminateEmployeeDataDownLoad" time="25.924" classname="sprint0.TerminatedEmployeeDownloadData">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [File already exist] but found [File does not exist]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [File already exist] but found [File does not exist]
at sprint0.TerminatedEmployeeDownloadData.testTerminateEmployeeDataDownLoad(TerminatedEmployeeDownloadData.java:42)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testTerminateEmployeeDataDownLoad -->
</testsuite> <!-- exampletest12 -->
